/*=============================================================================
 * TarotClub - DealFile.cpp
 *=============================================================================
 * Manage saving and loading XML files of custom deals
 *=============================================================================
 * TarotClub ( http://www.tarotclub.fr ) - This file is part of TarotClub
 * Copyright (C) 2003-2999 - Anthony Rabine
 * anthony@tarotclub.fr
 *
 * TarotClub is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * TarotClub is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with TarotClub.  If not, see <http://www.gnu.org/licenses/>.
 *
 *=============================================================================
 */

#include <sstream>
#include "JsonReader.h"
#include "JsonWriter.h"
#include "DealFile.h"
#include "defines.h"
#include "TarotDeck.h"
#include "Log.h"

static const std::string DEAL_FILE_VERSION  = "2.0";

/*****************************************************************************/
DealFile::DealFile()
{

}
/*****************************************************************************/
Deck &DealFile::GetNorthDeck()
{
    return mPlayers[Place::NORTH];
}
/*****************************************************************************/
Deck &DealFile::GetSouthDeck()
{
    return mPlayers[Place::SOUTH];
}
/*****************************************************************************/
Deck &DealFile::GetEastDeck()
{
    return mPlayers[Place::EAST];
}
/*****************************************************************************/
Deck &DealFile::GetWestDeck()
{
    return mPlayers[Place::WEST];
}
/*****************************************************************************/
Deck &DealFile::GetDogDeck()
{
    return mDogDeck;
}
/*****************************************************************************/
bool DealFile::LoadFile(const std::string &fileName)
{
    bool ret = true;
    JsonReader json;

    ret = json.Open(fileName);
    if (ret)
    {
        mDogDeck.Clear();
        for (int i = 0; i < 5; i++)
        {
            mPlayers[i].Clear();
        }

        std::string stringval;
        if (json.GetValue("", "version", stringval))
        {
            if (stringval == DEAL_FILE_VERSION)
            {
                if (json.GetValue("", "Dog", stringval))
                {
                    ret = FillDeck(mDogDeck, stringval, 6);
                }
                else
                {
                    TLogError("Cannot get dog deck");
                    ret = false;
                }

                for (std::uint32_t i = 0; i < 5; i++)
                {
                    if (ret)
                    {
                        Place player(i);
                        if (json.GetValue("", player.ToString(), stringval))
                        {
                            ret = FillDeck(mPlayers[i], stringval, 18);
                        }
                        else
                        {
                            TLogError("Cannot get dog deck");
                            ret = false;
                        }
                    }
                    else
                    {
                        TLogError("Cannot parse deck string");
                        ret = false;
                        break;
                    }
                }
            }
            else
            {
                TLogError("Wrong deal file version");
                ret = false;
            }
        }
        else
        {
            TLogError("Wrong deal file version");
            ret = false;
        }
    }
    json.Close();

    return ret;
}
/*****************************************************************************/
bool DealFile::FillDeck(Deck &deck, const std::string &cards, int nbCards)
{
    bool ret = false;

    if (deck.SetCards(cards) == nbCards)
    {
        ret = true;
    }
    else
    {
        TLogError("Wrong card list");
        ret = false;
    }

    return ret;
}
/*****************************************************************************/
void DealFile::SaveFile(const std::string &fileName)
{
    JsonWriter json;

    json.CreateValuePair("version", DEAL_FILE_VERSION);
    json.CreateValuePair("generator", "Generated by TarotClub " TAROT_VERSION);
    json.CreateValuePair("Dog", mDogDeck.GetCardList());

    for (std::uint32_t i = 0; i < 5; i++)
    {
        Place player(i);
        json.CreateValuePair(player.ToString(), mPlayers[i].GetCardList());
    }

    if (!json.SaveToFile(fileName))
    {
        TLogError("Saving custom deal file failed.");
    }
}


//=============================================================================
// End of file DealFile.cpp
//=============================================================================
